version: '3'
services:
  php-fpm:
    build:
      context: ./docker-prod/fpm
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: blx32/laravel-fpm:latest
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '.:/var/www/html'
    networks:
      - pol
    depends_on:
      - pgsql
      - redis
  nginx:
    build:
      context: ./docker-prod/nginx
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: blx32/laravel-nginx:latest
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
    volumes:
      - '.:/var/www/html'
    networks:
      - pol
    depends_on:
      - pgsql
      - redis
      - php-fpm
  pgsql:
    image: 'postgres:14-alpine3.18'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'pol-pgsql:/var/lib/postgresql/data'
      - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - pol
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'pol-redis:/data'
    networks:
      - pol
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
networks:
  pol:
    driver: bridge
volumes:
  pol-pgsql:
    driver: local
  pol-redis:
    driver: local
