<?php

namespace App\Models;

use App\Models\Scopes\TenantScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DirectMail extends Model
{
    use HasFactory;

    protected $fillable = [
        'person_id',
        'tenant_id',
        'received',
        'want_to_receive',
        'vote',
        'know_a_proposal',
        'indicate',
    ];

    protected $casts = [
        'received' => 'collection',
        'want_to_receive' => 'collection',
        'vote' => 'boolean',
        'know_a_proposal' => 'boolean',
        'indicate' => 'integer',
    ];

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            if (! app()->runningInConsole()) {
                $model->tenant_id = session()->get('tenant_id');
            }
        });
    }

    protected static function booted(): void
    {
        static::addGlobalScope(new TenantScope);
    }
}
